In [1]:
"""
@Author: Swapnil Bhoyar
@Date: 2021-07-11 18:16:00
@Last Modified by: Swapnil Bhoyar
@Last Modified time: 2021-08-11 18:16:00
@Title : Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array.
"""

In [4]:
import numpy as np
import Log

Write a Python program to convert a list of numeric value into a one-dimensional NumPy array.

In [ ]:
def ListToArray():
    """
    Description:
        this function convert list to numpy array
    """
    try:
        numberList = [21, 34, 45, 56]
        numberArray = np.array(numberList)
        Log.logging.info(numberArray)
    except Exception as e:
        Log.logging.error(e)

ListToArray()

Create a 3x3 matrix with values ranging from 2 to 10.

In [3]:
def createMatrix():
    """
    Description:
        this function create matrix.
    """
    try:
        numberMatrix = np.arange(2, 11).reshape(3, 3)
        Log.logging.info(numberMatrix)
    except Exception as e:
        Log.logging.error(e)

createMatrix()

Write a Python program to create a null vector of size 10 and update sixth value to 11.

In [4]:
def createVictor():
    """
    Description:
        this function create victor
    """
    try:
        zeroVictor = np.zeros(10)
        zeroVictor[6] = 11
        Log.logging.info(zeroVictor)
    except Exception as e:
        Log.logging.error(e)

createVictor()

Write a Python program to reverse an array (first element becomes last).
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [6]:
def reverseArray():
    """
    Description:
        this function reverse the array
    """
    try:
        numberArray = np.arange(12, 38)
        numberArray = numberArray[::-1]
        Log.logging.info(numberArray)
    except Exception as e:
        Log.logging.error(e)

reverseArray()

Write a Python program to create a 2d array with 1 on the border and 0 inside.
Expected Output:
Original array:
[[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 1. 1. 1. 1. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 1. 1. 1. 1.]]

In [7]:
def twoDArray():
    """
    Description:
        this function create padding
    """
    try:
        numberArray = np.zeros((4, 4))
        numberArray = np.pad(numberArray, pad_width=1, mode='constant', constant_values=1)
        Log.logging.info(numberArray)
    except Exception as e:
        Log.logging.error(e)

twoDArray()

Write a Python program to add a border (filled with 0's) around an existing array.

In [8]:
def addBorder():
    """
    Description:
        this function add pading to array
    """
    try:
        tempArray = np.ones((3, 3))
        tempArray = np.pad(tempArray, pad_width=1, mode='constant', constant_values=0)
        Log.logging.info(tempArray)
    except Exception as e:
        Log.logging.error(e)

addBorder()

Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [12]:
def checkerBoard():
    """
    Description:
        this function create checkerboard.
    """
    try:
        tempArray = np.zeros((8, 8))
        tempArray[1::2,::2] = 1
        tempArray[::2,1::2] = 1
        Log.logging.info(tempArray)
    except Exception as e:
        Log.logging.error(e)

checkerBoard()

Write a Python program to convert a list and tuple into arrays.
List to array:
[1 2 3 4 5 6 7 8]
Tuple to array:
[[8 4 6]
[1 2 3]]

In [14]:
def convertToArray():
    """
    Description:
        this function convert list and tuple to array
    """
    try:
        tempList = [1, 2, 3, 4, 5, 6, 7, 8]
        tempArray = np.asarray(tempList)
        Log.logging.info(tempArray)
        tempTuple = ([8, 4, 6],[1, 2, 3])
        tempArray = np.asarray(tempTuple)
        Log.logging.info(tempTuple)
    except Exception as e:
        Log.logging.error(e)

convertToArray()

Write a Python program to append values to the end of an array.
Expected Output:
Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]

In [15]:
def appendToArray():
    """
    Description:
        this function append at the end
    """
    try:
        numberList = [10, 20, 30]
        numberList = np.append(numberList, [40, 50, 60, 70])
        Log.logging.info(numberList)
    except Exception as e:
        Log.logging.error(e)

appendToArray()

Write a Python program to find the real and imaginary parts of an array of complex
numbers.
Expected Output:
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]
Real part of the array:
[ 1. 0.70710678]
Imaginary part of the array:[ 0. 0.70710678]

In [16]:
def realAndImaginary():
    """
    Descriptio:
        this function print real and imagenary part
    """
    x = np.sqrt([1+0j])
    y = np.sqrt([0+1j])
    Log.logging.info("Real part of array:")
    Log.logging.info(x.real)
    Log.logging.info(y.real)
    Log.logging.info("Imagenary part of array:")
    Log.logging.info(x.imag)
    Log.logging.info(y.imag)

realAndImaginary()

Write a Python program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.

In [5]:
def totalBytes():
    """
    Dscription:
        this function calculate total byte of array
    """
    try:
        numberArray = np.array([11, 23, 34, 45])
        Log.logging.info("size:")
        Log.logging.info(numberArray.size)

        Log.logging.info("length of one element:")
        Log.logging.info(numberArray.itemsize)

        Log.logging.info("total bytes:")
        Log.logging.info(numberArray.nbytes)
    except Exception as e:
        Log.logging.error(e)

totalBytes()

Write a Python program to find common values between two arrays.
Expected Output:
Array1: [ 0 10 20 40 60]
Array2: [10, 30, 40]
Common values between two arrays:
[10 40]

In [6]:
def commonValues():
    """
    Description:
        this function find common values
    """
    try:
        firstArray = np.array([0, 10, 20, 40, 60])
        secondArray = np.array([10, 40])

        Log.logging.info(np.intersect1d(firstArray, secondArray))
    except Exception as e:
        Log.logging.error(e)

commonValues()

Write a Python program to find the set difference of two arrays. The set difference
will return the sorted, unique values in array1 that are not in array2.
Expected Output:
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70, 90]
Set difference between two arrays:
[ 0 20 60 80]

In [7]:
def UniqueElements():
    """
    Description:
        this function finds unique elements
    """
    try:
        firstArray = np.array([0, 10, 20, 40, 60, 80])
        secondArray = np.array([10, 30, 40, 50, 70])
        Log.logging.info(np.setdiff1d(firstArray, secondArray))
    except Exception as e:
        Log.logging.error(e)

UniqueElements()

Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or
will return the sorted, unique values that are in only one (not both) of the input arrays.
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]

In [ ]:
def exclusiveOr():
    """
    Description:
        this function find unique element from both array
    """
    try:
        firstArray = np.array([0, 10, 20, 40, 60, 80])
        secondArray = np.array([10, 30, 40, 50, 70])
        Log.logging.info(np.setxor1d(firstArray, secondArray))
    except Exception as e:
        Log.logging.info(e)

exclusiveOr()